# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pilot < Formula
  desc "AI that ships your tickets — autonomous development pipeline"
  homepage "https://pilot.quantflow.studio"
  version "2.148.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qf-studio/pilot/releases/download/v2.148.0/pilot-darwin-amd64.tar.gz"
      sha256 "ec408fe9455d2afa0ac5ac8803a7697e0c4eb5f862a34a5e8a729c644c1a0040"

      define_method(:install) do
        bin.install "pilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qf-studio/pilot/releases/download/v2.148.0/pilot-darwin-arm64.tar.gz"
      sha256 "2e6adf586449254b9feee6efa02d0ea1e4b008e0d7e1119754358dc6fe854926"

      define_method(:install) do
        bin.install "pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qf-studio/pilot/releases/download/v2.148.0/pilot-linux-amd64.tar.gz"
      sha256 "e261c87413fee374857f58a5a73777fe8234998d71b17f383c08d48b6a5fca5b"
      define_method(:install) do
        bin.install "pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qf-studio/pilot/releases/download/v2.148.0/pilot-linux-arm64.tar.gz"
      sha256 "82aae51a8cab2f919e3585a9474e91d5bf1d75f6da7dc8b57e1e89c8edac1eaa"
      define_method(:install) do
        bin.install "pilot"
      end
    end
  end

  test do
    system "#{bin}/pilot", "version"
  end
end
