# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pilot < Formula
  desc "AI that ships your tickets — autonomous development pipeline"
  homepage "https://pilot.quantflow.studio"
  version "2.106.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qf-studio/pilot/releases/download/v2.106.1/pilot-darwin-amd64.tar.gz"
      sha256 "db48e886810a15cecde75d00bc9f9386297f4c4fa1b6ed045e046217b73f60e5"

      define_method(:install) do
        bin.install "pilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qf-studio/pilot/releases/download/v2.106.1/pilot-darwin-arm64.tar.gz"
      sha256 "56e528a2dc6a2880dee77c673cabff8caa5ab9eec27e731c6dd6a3325a62c3fc"

      define_method(:install) do
        bin.install "pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qf-studio/pilot/releases/download/v2.106.1/pilot-linux-amd64.tar.gz"
      sha256 "212bd1ea9ee28dc51e7ce1f94fbb23974c6ccc67d5c8db2b890c0a8e1bfb7868"
      define_method(:install) do
        bin.install "pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qf-studio/pilot/releases/download/v2.106.1/pilot-linux-arm64.tar.gz"
      sha256 "7ead53320eca991b76030c834d9094cf4b416d554b9a3e7e247903717c443c07"
      define_method(:install) do
        bin.install "pilot"
      end
    end
  end

  test do
    system "#{bin}/pilot", "version"
  end
end
